### ISSUE TITLE
Brackets Extension Manager doesn't contain latest version

### ISSUE THREAD

**Issue by yahyaKacem** [zaggino/brackets-eslint#1]
I'm on ubuntu 14.04 using latest brackets Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97) I installed this plugin with the package manager, and put this .eslintrc file in the root of my project.

but Brackets give me this error in the ESLint console:
>ESLint terminated with error: Definition for rule 'comma-dangle' was not found.	

removing that line give me this error:
>ESLint terminated with error: Definition for rule 'semi-spacing' was not found.	

removing both works correctly.
if those are deprecated please update this [file](https://github.com/zaggino/brackets-eslint/blob/master/.eslintrc) to say so, and thanks for this plugin.
and it would be awesome if I could manually run this or set it to run on each save.

**Comment by zaggino** [comment]
Hi, use this way to install the extension: https://github.com/zaggino/brackets-eslint#install

Brackets' extension manager is broken, it doesn't allow me to upload the latest version (`comma-dangle` and `semi-spacing` are new rules introduced in `0.16.0`, the version in the extension manager is broken.

To execute ESLint on every file save in a project, place `.brackets.json` file in your project root: https://github.com/zaggino/brackets-eslint/blob/master/.brackets.json#L6-L9

**Comment by zaggino** [comment]
Use https://github.com/zaggino/brackets-npm-registry from now on to install/update this extension.
