### ISSUE TITLE
Support globally installed plugins

### ISSUE THREAD

**Issue by AdriVanHoudt** [zaggino/brackets-eslint#10]
Is there a possibility to properly support custom plugins? I had to install the plugin in the brackets-eslint project to make it work. The standard cli seems to find the plugin fine.

**Comment by zaggino** [comment]
There should be, but my first attempt on this failed. I'll look into this more when I'll have time.

**Comment by AdriVanHoudt** [comment]
if you are using the cli shouldn't it find the global plugins automatically?

**Comment by zaggino** [comment]
No, this is using the `CLIEngine` provided by ESLint, I've tried setting the `NODE_PATH` but for some reason it didn't work to include the global plugins.

https://github.com/zaggino/brackets-eslint/blob/master/domain.js#L8-L9

**Comment by AdriVanHoudt** [comment]
hmm the engine doesn't seem to work as the cli. normally it should see globally installed plugins (bug?) you could however add some config for it where you specify the plugin names and then `npm install` it into brackets-eslint. Not sure if that is a good solution though

**Comment by zaggino** [comment]
I've tried using https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders
`NODE_PATH` environment variable set to location where global node modules are installed.

If I set I globally in my system, it works fine.
If I try to set it through `process.env.NODE_PATH=...` in `domain.js` file where `ESLint` is loaded, it doesn't work ... seems like node's `require` ignores modifications to `NODE_PATH` during the execution itself

**Comment by zaggino** [comment]
So current workaround (not a solution I'd want) for custom modules to work is setting the `NODE_PATH` in the system, on my PC works: `NODE_PATH=C:\Users\Zaggi\AppData\Roaming\npm\node_modules`

**Comment by zaggino** [comment]
Oh, I may have found a dirty private variable abusing workaround :)
```
process.env.NODE_PATH = 'C:\\Users\\Zaggi\\AppData\\Roaming\\npm\\node_modules';
require('module').Module._initPaths();
```

**Comment by zaggino** [comment]
Ok - in latest master, globally installed plugins work both on windows & linux. I'll add the correct mac path tomorrow and publish a new version of the extension.

https://github.com/zaggino/brackets-eslint/blob/master/domain.js#L7-L20

**Comment by AdriVanHoudt** [comment]
cool thanks!

**Comment by zaggino** [comment]
fixed in `brackets-eslint@0.19.1`
details in https://github.com/zaggino/brackets-eslint#additional-parsers-and-plugins
please close if fixed for you, thanks!

**Comment by AdriVanHoudt** [comment]
hmm I have stuff in that path that works but if I `npm install -g` now it goes to ` c:\Program Files\nodejs\node_modules\npm` not sure why

**Comment by zaggino** [comment]
You have some kind of non-standard nodejs installation?

**Comment by AdriVanHoudt** [comment]
probably :D I have `C: \Users\adri\AppData\Roaming\npm` in my PATH maybe that has something to do with it?

**Comment by AdriVanHoudt** [comment]
I have used a node version manager before so maybe that messed things up. I'll try uninstalling and reinstalling node

**Comment by AdriVanHoudt** [comment]
Ok I uninstalled node and removed the 'special' npm location and then reinstalled node. Everything works now. Thanks for the effort!
