### ISSUE TITLE
how to install so brackets can use it???

### ISSUE THREAD

**Issue by keitha-cakewalk** [zaggino/brackets-eslint#12]
I feel like I'm in a circular reference.  I have brackets-npm-registry correctly installed.
It appears in the brackets app as an Installed extension.  ESLint is listed in available but not compatible with version, click the more info link which loads the brackets-npm-registry page.  
I have tried doing npm install brackets-eslint as well as npm install eslint within the brackets-npm-registry folder.  Both are listed in the node_modules subfolder.  
Thanks in advance!  Have recently found eslint which I have globally uninstalled and reinstalled and it works on cmd line.  Please let me know how to 'use brackets-npm-registry to install'

**Comment by keitha-cakewalk** [comment]
Nevermind!  Just found the little npm button aha, so that's how it's done.

**Comment by keitha-cakewalk** [comment]
This integration is AWESOME! THANKS!!!

**Comment by zaggino** [comment]
:+1: glad you figured it out :)
