### ISSUE TITLE
support .eslintignore?

### ISSUE THREAD

**Issue by waffledonkey** [zaggino/brackets-eslint#15]
I was wondering if the roadmap includes a plan to support .eslintignore.  The same can be achieved using the inline comment syntax, but some of the js files come from bower and I'm reluctant to touch them as it feels like a slippery slope.  In some cases the files are so physically large (maybe?) that it completely hangs brackets. :(  I went to see what version of jQuery was in a project and should have started with bower list from terminal, but I clicked on the file in the list and brackets completely locked up.

**Comment by zaggino** [comment]
Thanks for the issue, this should definitely be supported.
For reference: http://eslint.org/docs/user-guide/configuring.html#ignoring-files-and-directories

**Comment by zaggino** [comment]
This feature should be now supported in the latest version of `brackets-eslint`. Can you update and provide feedback please? Thanks

**Comment by waffledonkey** [comment]
That seems to work a treat, thanks.

:::air five:::
