### ISSUE TITLE
ignore minified files

### ISSUE THREAD

**Issue by waffledonkey** [zaggino/brackets-eslint#16]
I was pleasantly surprised to see Miguel Castillo's interactive linter ignore minified files and was wondering if you had plans to do something similar.  It's a fairly weak test in that it just looks at the amount of whitespace in a file, but it works well enough and is better than nothing.

**Comment by zaggino** [comment]
Yes, I can definitely do this when I'll have some free time.

**Comment by zaggino** [comment]
Isn't this covered by https://github.com/zaggino/brackets-eslint/issues/15 ?
