### ISSUE TITLE
Upgrade to eslint  0.16.2

### ISSUE THREAD

**Issue by stoffeastrom** [zaggino/brackets-eslint#2]
Trying to use this with es6 but currently there is a bug that should be solved in latest eslint
http://eslint.org/blog/2015/03/eslint-0.16.2-released/

**Comment by zaggino** [comment]
Latest version with `0.16.2` is in the master, but you have to install it manually for now:
https://github.com/zaggino/brackets-eslint#install

I'm working on method for installing extensions directly from npm but it's not ready yet.
