### ISSUE TITLE
ESLint terminated with error: cleanup (continued...)

### ISSUE THREAD

**Issue by petetnt** [zaggino/brackets-eslint#20]
Continuing from adobe/brackets/issues/11613 (and adobe/brackets/issues/10842 and zaggino/brackets-eslint/issues/14...)

While trying to debug this issue, I have tried all the steps mentioned in adobe/brackets/issues/11613 (disabling NodeSearch, running from a lightning fast SSD instead of a network drive...) plus things like removing all the global modules, removing all the extensions sans `brackets-eslint` related one by one, using `AppInit` to wait until everything has been loaded in `brackets-eslint` and this is still happening no matter what. 

There is one gotcha though: ESLint works as intended **if the file that's open on launch isn't a JavaScript file**.

1. Open index.html
2. Close Brackets
3. Open Brackets
4. Navigate to Foo.js
5. Eslint works as intended
6. Close Brackets
7. Open Brackets
8. ESLint terminated with error: cleanup -> Restart Node -> 
![image](https://cloud.githubusercontent.com/assets/7641760/10011884/dae1c086-6109-11e5-8203-54c73de56d63.png) 
-> Have to restart whole app again

I still have no idea what's actually causing it and I am quite sure that it is actually an issue how Brackets handles domain. The reason I am reposting this here is to brainstorm on some ideas how to avoid this (in `brackets-eslint` or otherwise), workarounds or just bug fixes with an hammer.

**Comment by zaggino** [comment]
`Cleanup` means that Brackets got disconnected from Node, in case of `brackets-git` it happens when I try to send a large message through socket but `brackets-eslint` should never produce messages that large. It's interesting it happens only on startup. I'm using `NodeDomain` utility here, it might be worth exploring if it reconnects correctly when disconnected. In `brackets-git` I use manual solution which reconnects quite well on failure, here I thought I make it easier.

**Comment by zaggino** [comment]
@petetnt does brackets-git work well for you on your machine? I can't replicate this but if yes, I can port some of brackets-git internals into brackets-eslint to see, if it fixes your problem.

**Comment by petetnt** [comment]
@zaggino Tried out brackets-git just now (awesome extension btw!) and it works perfectly as far as I can see.

**Comment by zaggino** [comment]
@petetnt I have published `brackets-eslint@1.5.0`, can you please try that one? It might take 15-20 for npm registry to update. Let me know how did you go please.

**Comment by petetnt** [comment]
@zaggino `brackets-eslint@1.5.0` fixed all the problems I were having. Thanks a ton :+1:

**Comment by zaggino** [comment]
Cool :+1:
