### ISSUE TITLE
Extension requires a newer version of Brackets

### ISSUE THREAD

**Issue by soluml** [zaggino/brackets-eslint#21]
If you search for this extension in the Brackets (1.5) repo, you'll find that there's a yellow message stating that the user needs a newer version of Brackets to install this plugin.  Brackets 1.5 is the latest as of this writing.

Looks like the [`engines.brackets`](https://github.com/adobe/brackets/wiki/Extension-package-format#details) property in your [package.json](https://github.com/zaggino/brackets-eslint/blob/master/package.json#L40) is formatted incorrectly.  Should be something like:

    "engines": {
        "brackets": ">=0.42.0"
    }

**Comment by zaggino** [comment]
@soluml see README: https://github.com/zaggino/brackets-eslint#how-to-install

this extension is not possible to install without npm so you'll need to use [brackets-npm-registry](https://github.com/zaggino/brackets-npm-registry)
