### ISSUE TITLE
Doesn't work with locally installed packages

### ISSUE THREAD

**Issue by ForbesLindesay** [zaggino/brackets-eslint#24]
I wanted to use this with my project, but I use a preset that I install via npm.  Because we want to make sure everyone on the project has the same version of the preset, we install it locally as a `devDependency`.  This is the generally recommended best practice.

Unfortunately, brackets-eslint seems to only load packages that have been installed globally.  Could it be fixed to load local packages as well?

**Comment by ForbesLindesay** [comment]
It would also be great if it could use the locally installed copy of eslint where possible.  That would help ensure everyone stayed properly in sync with the project.

**Comment by zaggino** [comment]
Hi, yes, definitely, I'll have a look at it.

**Comment by zaggino** [comment]
@ForbesLindesay Upgraded to `brackets-eslint@2.1.0`. Locally installed plugins (and also ESLint itself) should be now picked up before global ones.
