### ISSUE TITLE
Does not install using standard tools

### ISSUE THREAD

**Issue by TotallyInformation** [zaggino/brackets-eslint#25]
Hi, not sure why you've decided not to use the standard package manager?

I really don't want to have to think about 2 different ways of installing and updating packages for my editor, it is really annoying.

Please consider changing to support the standard package manager so that we can all enjoy the benefits of ESLint without having to mess around.

**Comment by zaggino** [comment]
Due to limits of standard package manager for Brackets, it's not possible to include `node_modules` with large size and large amount of files in the package. 

Related: https://github.com/adobe/brackets/pull/10602

**Comment by TotallyInformation** [comment]
OK, thanks for clarifying. I still can't quite work out whether I prefer Atom or Brackets. Neither is really perfect.
