### ISSUE TITLE
Getting this eslint error

### ISSUE THREAD

**Issue by ckoo7** [zaggino/brackets-eslint#27]
![screenshot from 2016-02-11 16-58-22](https://cloud.githubusercontent.com/assets/8359963/12975346/db0c1c22-d0e0-11e5-9398-c74fec9a6129.png)
How to solve this issue

**Comment by zaggino** [comment]
That seems like an error in the react plugin for ESLint, not the ESLint itself

**Comment by ckoo7** [comment]
Thanx
