### ISSUE TITLE
Parsing error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by AdriVanHoudt** [zaggino/brackets-eslint#28]
Not sure why but somehow it started giving me this error.
I have `es6: true` in my .eslintrc.js
Running eslint from command line works fine and setting env inline in the file also works

any ideas on how to fix or debug?
I tried: reinstall (hence how I found the registry error ;)), using `root: true`, using old .eslintrc

**Comment by zaggino** [comment]
@AdriVanHoudt if `brackets-eslint` founds a eslint in your project (https://github.com/zaggino/brackets-eslint/blob/master/domain.js#L62) then it'll use that version and version installed by npm-registry won't matter. Check your project if you don't have an old version of eslint maybe?

**Comment by AdriVanHoudt** [comment]
I logged cli and current version (https://github.com/zaggino/brackets-eslint/blob/master/domain.js#L118-L119:

```js
{ options: 
   { configFile: null, // shouldn't this contain my config?
     baseConfig: false,
     rulePaths: [],
     useEslintrc: true,
     envs: [],
     globals: [],
     rules: {},
     extensions: [ '.js' ],
     ignore: true,
     ignorePath: '[path to project root]/.eslintignore',
     parser: 'espree',
     cache: false,
     cacheLocation: '',
     cacheFile: '.eslintcache',
     fix: false,
     allowInlineConfig: true,
     cwd: '/' },
  _fileCache: 
   { cache: { _visited: {}, _persisted: {}, _pathToFile: '/.eslintcache' },
     hasFileChanged: [Function],
     analyzeFiles: [Function],
     getFileDescriptor: [Function],
     getUpdatedFiles: [Function],
     normalizeEntries: [Function],
     removeEntry: [Function],
     deleteCacheFile: [Function],
     destroy: [Function],
     reconcile: [Function] } }
2.7.0
```
it is missing the config file? (version is fine btw)

**Comment by zaggino** [comment]
When `useEslintrc: true` you shouldn't need to specify path to config file. I use this extension across about 8-10 projects daily with different configs and it works fine, most of them use `const` too. But feel free to experiment, maybe you ran into some edge case or something.

**Comment by AdriVanHoudt** [comment]
yeah I have used it too across many different projects, it somehow broke for some reason :(

**Comment by zaggino** [comment]
If I check here: http://eslint.org/docs/user-guide/configuring
With latest eslint, it should be `"ecmaVersion": 6,` and not `es6: true` ?

**Comment by zaggino** [comment]
Does your project work fine if you check it using `eslint 2.7.0` from command line? Without Brackets?

**Comment by AdriVanHoudt** [comment]
es6: true is still a thing, tried with ecmaVersion but no difference, I made a new js file and it does not lint with my config at all

yes it works with running `eslint .` in project root

**Comment by zaggino** [comment]
I'm guessing it's not something you have lying around publicly on github? :)

**Comment by AdriVanHoudt** [comment]
the project or config?

also switched to another project with it's own eslintrc and that uses const and no error, switch back, const error gone but now complains about default rules (like indents), owke...

**Comment by zaggino** [comment]
well, the whole repo with config ... or at least a config with a file which replicates the problem when I fetch it

**Comment by AdriVanHoudt** [comment]
this errors for me https://gist.github.com/AdriVanHoudt/2a1f92e22a966cc16a86ad4350aca81c

**Comment by AdriVanHoudt** [comment]
ok switched from that thing to my repo and now works fine O_0

**Comment by AdriVanHoudt** [comment]
restart brackets, fails again... some wizardry going on

**Comment by zaggino** [comment]
Try removing the `extends: 'eslint-config-hapi',` from your config ...

**Comment by AdriVanHoudt** [comment]
nope :/

**Comment by zaggino** [comment]
That's weird, I only get the `const` error when eslint-config-hapi extension is enabled. If I remove it, restart, validation passes.

**Comment by zaggino** [comment]
Seems like some parts don't reload when switching files/projects how they should, I'll investigate that point soon next week.

**Comment by AdriVanHoudt** [comment]
cool, thanks for helping!

**Comment by zaggino** [comment]
@AdriVanHoudt try `brackets-eslint@2.1.4`

**Comment by AdriVanHoudt** [comment]
seems to be working! thank you so much! :tada:

**Comment by zaggino** [comment]
Happy to help ;)

**Comment by amarneethi** [comment]
I have this same error. Where do I add this brackets-eslint@2.1.4? 
I'm sorry if this is a dumb question I'm new to config files.

**Comment by zaggino** [comment]
@amarneethi To the `.eslintrc` file in your project. Read more about it here https://eslint.org/docs/user-guide/configuring

**Comment by AkashGalani** [comment]
ESLint defaults to ES5 syntax-checking. You’ll want to override to the latest well-supported version of JavaScript.

Try adding a .eslintrc file to your project. Inside it:

{
"parserOptions": {
"ecmaVersion": 2017
},

"env": {
"es6": true
}
}

Example [Here](https://icetutor.com/question/eslint-error-parsing-error-the-keyword-const-is-reserved/)
