### ISSUE TITLE
Error after manual install

### ISSUE THREAD

**Issue by stoffeastrom** [zaggino/brackets-eslint#3]
I get this error after manual install
ESLint terminated with error: Unable to load one of the modules: C:/Users/cam/AppData/Roaming/Brackets/extensions/user/brackets-eslint/domain, reason: Command zaggino.brackets-eslint.lintFile already registered	

win7

**Comment by zaggino** [comment]
check the extensions directory for the one installed from brackets registry and delete it, it should be called something like `zaggino.brackets-eslint` manually installed one has directory `brackets-eslint` and when you have both, they will conflict

**Comment by stoffeastrom** [comment]
It was called zaggino.brackets-git
Works!

**Comment by kmturley** [comment]
I'm getting a similar error:

    ESLint terminated with error: Unable to load one of the modules: C:/Users/Kim T/AppData/Roaming/Brackets/extensions/user/brackets-eslint/domain, reason: Cannot find module 'eslint'

Windows 10.

I presume this is because the eslint module is not installed? I tried this but no luck:

    npm install eslint -g

**Comment by zaggino** [comment]
@kmturley Did you do the `npm install` in the `C:/Users/kmt/AppData/Roaming/Brackets/extensions/user/brackets-eslint` directory? Has it created `node_modules` with `eslint` inside it?

**Comment by kmturley** [comment]
Yep, it didn't have the npm_modules folder after installation (is this a bug?). So then I tried the following command within the directory C:\Users\kmt\AppData\Roaming\Brackets\extensions\user\brackets-eslint:

    npm install

That has fixed it. I needed to restart Brackets to get it to work!

**Comment by zaggino** [comment]
It is not a bug, it is your mistake :)
If you've used brackets-npm-registry, it executes npm install automatically.

**Comment by kmturley** [comment]
ah gotcha, thanks!
