### ISSUE TITLE
Global node modules not found

### ISSUE THREAD

**Issue by marianobianchi** [zaggino/brackets-eslint#35]
Hello,

I recently started to write some code using AngularJS and I'm getting used to work in nodejs/npm environments. When configuring my global npm modules path I followed [these](https://docs.npmjs.com/getting-started/fixing-npm-permissions) instructions.

Later, when I tried to use this brackets extension with angularjs plugin I got an error saying that the plugin wasn't found although I have installed it before globally. Looking in the code I found that "NODE_PATH" environment variable was used to search for npm installed modules (see [1])

Then I looked over npm documentation and it describe the prefix configuration as the folder structure used in npm (see [2]).

I solved my problem adding `npm config get prefix`/lib/node_modules to NODE_PATH. It would be great if you can add this to the readme or change/improve the code to search in npm prefix folder.

If you think I can help you with a PR, I can try to solve it.

[1] https://github.com/zaggino/brackets-eslint/blob/39de935fd9b9cb456bb696322dc000f03326e1be/domain.js#L97
[2] https://docs.npmjs.com/files/folders#prefix-configuration

**Comment by zaggino** [comment]
`NODE_PATH` env variable should be enough (it is on my pcs) but if you want to submit a PR to check the `npm config get prefix` then go ahead, it'll be welcome if it fixes situation on your machine
