### ISSUE TITLE
eslint@3.x support not possible until brackets update bundled node version to 4.x

### ISSUE THREAD

**Issue by sradevski** [zaggino/brackets-eslint#36]
The extension cannot load the eslint client. I tried installing eslint globally and locally, both running fine, but when run from Brackets.io it cannot load the client. I am running brackets on MacBook Pro, El Capitan.

**Comment by AdriVanHoudt** [comment]
I am having the same issue here. I think this has to do with eslint 3 requiring node >= 4, @zaggino any suggestions on how this could be solved? Seems like Brackets needs to update it's internal version of node or could this plugin do this?

**Comment by zaggino** [comment]
hmm, extension probably won't be able to do anything with this, it's brackets problem

**Comment by AdriVanHoudt** [comment]
do you know if brackets has an initiative to up the node version?

**Comment by zaggino** [comment]
@AdriVanHoudt I don't believe brackets have an initiative to do anything except get the brackets code to new dreamweaver at the moment, atom or vs-code might be better alternatives at the moment

**Comment by AdriVanHoudt** [comment]
new dreamweaver? Also I just updated and it works again, I think it i fine as long as my config does not include eslint > 3 rules

**Comment by AdriVanHoudt** [comment]
Ok so it works when my project also has an eslint of < 3 :/

**Comment by zaggino** [comment]
@AdriVanHoudt 
http://blog.brackets.io/2015/10/05/update-from-the-adobe-brackets-team/
http://blogs.adobe.com/dreamweaver/2015/10/next-generation-of-dreamweaver.html

**Comment by AdriVanHoudt** [comment]
Hmm feels like the project is slightly dying out seeing how old that is and looking at the recent commits, which are mostly translation updates

**Comment by zaggino** [comment]
@sradevski @AdriVanHoudt published `brackets-eslint@2.6.0`

i put a check if it detects eslint@3.x, then fallback to use latest eslint@2.x instead of failing completely

only thing I could think of

**Comment by AdriVanHoudt** [comment]
@zaggino I am not seeing the plugin in npm registry any more, I can see it in the plugins thing  but that is v 0.17 and it does not allow me to install it. Any way you unpublished it or something?

**Comment by zaggino** [comment]
@AdriVanHoudt Nothing is unpublished, registry builder uses `npmsearch.com` site to search for extensions but it seems quite unreliable. Must look at some other npm search provider.

**Comment by AdriVanHoudt** [comment]
ah I see, weird that it can't find just that one, no way you can use npm's api (if they have one)?

**Comment by zaggino** [comment]
They don't, not that I know of. I'll try to get it up and running somehow.

**Comment by AdriVanHoudt** [comment]
@zaggino thanks a lot for the effort! 🔥

**Comment by zaggino** [comment]
@AdriVanHoudt pushed out new server version of `brackets-npm-registry` using actual urls that npm itself calls (by debugging the client) and `brackets-eslint` is back in there ;)

**Comment by AdriVanHoudt** [comment]
@zaggino seems to work now! Now since the last eslint release it messed something up with the indent so I needed to add a config to the rule which eslint 2 does not like :( dumb that v2 does not just ignore it
hopefully brackets will update to node 4 or up. If there is no intention to I might switch IDE sadly

**Comment by zaggino** [comment]
@AdriVanHoudt doing progress of getting new node (and eslint 3.x support with it) into brackets: https://github.com/adobe/brackets/pull/12647

**Comment by AdriVanHoudt** [comment]
@zaggino following it and looks great!

**Comment by zaggino** [comment]
@AdriVanHoudt this is now fixed in https://github.com/zaggino/brackets-electron/releases
still waiting for the team to approve changes to land in regular brackets too

**Comment by zaggino** [comment]
Latest pre-release of Brackets supports this too: https://github.com/adobe/brackets/releases
