### ISSUE TITLE
Auto-fix doing nothing

### ISSUE THREAD

**Issue by PeterVermont** [zaggino/brackets-eslint#39]
I am using Barackets Release 1.7 build 1.7.0-16898 (release b0a363b71) with brackets-eslint 2.5.0 installed by url.

Auto-fix seems to have no affect.

**Comment by zaggino** [comment]
@PeterVermont  if you use command line with `--fix` does it do something? Extension is just supposed to do that. It doesn't fix every problem.

http://eslint.org/docs/user-guide/command-line-interface

**Comment by MynockSpit** [comment]
Getting this same issue. Doing --fix from the command line works, but using the both the right-click menu and the option in the edit menu seem not to. No errors in the console, either.
