### ISSUE TITLE
Support for custom rules

### ISSUE THREAD

**Issue by Hirse** [zaggino/brackets-eslint#4]
ESLint allows to specify a directory from which to load rules files with the `--rulesdir` option.
The [ESLint CLIEngine](http://eslint.org/docs/developer-guide/nodejs-api#cliengine) has an option `rulePaths` which has the same functionality.

I suggest to search for folders with the name `.eslintrules` in the open project and add them to the rulePaths.
When I call ESLint from the project root on the command line, I can even use a wildcard to add a rules from anywhere in the project:
`eslint --rulesdir */.eslintrules src/ui`

**Comment by zaggino** [comment]
Definitely can do this - do you have any public repo I can test this on?

**Comment by Hirse** [comment]
Sorry, no I don't. I would like to have this for work, but that code is not public naturally.
You can try this as rule:
```js
module.exports = function(context) {
	"use strict";
	return {
		"CallExpression" : function(node) {
			if (node.callee.type === "MemberExpression" && node.callee.property.type === "Identifier") {
				if (node.callee.object.name === "window" && node.callee.property.name === "alert") {
					context.report(node, "A window.alert statement should not be part of the code that is committed to GIT!");
				}
			}
		}
	};
};
```
Save it as `.eslintrules/no-window-alert.js` and add `"no-window-alert": 1,` to the rules.

**Comment by zaggino** [comment]
Thanks. I'll finish this after the weekend. The sample rule is enough :)

**Comment by zaggino** [comment]
@Hirse `brackets-eslint@0.17.2` has been published to npm which solves this, see [README](https://github.com/zaggino/brackets-eslint) for details.

**Comment by Hirse** [comment]
Sorry, I didn't give any feedback before. 
I tested it as soon as you merged the changes, but must have forgotten to reply.
Thanks for your good work.
