### ISSUE TITLE
Hover tooltip on guttermarks

### ISSUE THREAD

**Issue by Iskander508** [zaggino/brackets-eslint#40]
Could a tooltip with eslint warning/error message text be displayed when hovering by mouse over the guttermarks? It's a bit clumsy to lookup the message using line number in the (bottom) report panel.

**Comment by zaggino** [comment]
Added in `2.9.0`

![image](https://cloud.githubusercontent.com/assets/1067319/17465587/7ac07918-5d3e-11e6-9c30-1deedbd28538.png)

**Comment by Iskander508** [comment]
Perfect job!
