### ISSUE TITLE
Extension error by brackets

### ISSUE THREAD

**Issue by ReyPena** [zaggino/brackets-eslint#43]
So I had this error #42 and I try to install it manually but after manual installation brackets tell me no linter available for JavaScript.
manual installation been:
```
cd ~/Library/Application\ Support/Brackets/extensions/user/
git clone https://github.com/zaggino/brackets-eslint brackets-eslint
cd brackets-eslint
npm install
```
I run `npm test` to check if there was something wrong on the build but no error any way to fix this ?
brackets -v 1.7

**Comment by zaggino** [comment]
No idea, I have just installed the extension in a same way and it works.

**Comment by ReyPena** [comment]
When I do this is like the eslint extension is not there and brackets tell me that there is not a linter for JavaScript.

**Comment by zaggino** [comment]
@ReyPena can you provide full logs from the error console (F12) ?
