### ISSUE TITLE
disabling JSLint in favour of ESLint

### ISSUE THREAD

**Issue by GusGF** [zaggino/brackets-eslint#44]
Sorry to ask this as it's not something you should be answering but I've installed ESLint but JSLint is still active in Brackets how can I disable JSLink in favour of ESLint and have it so for all new files/scripts.

**Comment by GusGF** [comment]
It's okay got my answer...you can turn off JSLint completely in Brackets by unchecking View > Lint Files on Save.

**Comment by zaggino** [comment]
Disabling `Lint Files on Save` disables all code linting, so brackets-eslint too. Proper way would be to delete the JSLint default extension from the Brackets folder.

**Comment by GusGF** [comment]
Hi Martin,
Thanks for all your help. I've deleted the JSLint folder and that's got rid of the pesky warnings from JSLint. :)
