### ISSUE TITLE
Have I installed properly ESLint?

### ISSUE THREAD

**Issue by GusGF** [zaggino/brackets-eslint#45]
As a complete newbie to JS I've got a simple brackets project. I can run a JS script and it works. But I'm not sure ESLint is activated as when I change the JS code to throw an error nothing comes up so there is no sign ESLint is working and activated (JSLint in contrast was throwing up so many messages ). I've followed the installation steps and can see ESLint in the Brackets extension manager and the brackets-npm-registry both confirm the linter is installed. I've tried searching for answers and your wiki page for this project is empty and there doesn't seem to be any instructions for someone like myself who is new to this. Hope you can help.

BTW the embedded link below does not work....
How to configure
Use standard .eslintrc file like this one

**Comment by GusGF** [comment]
Okay realised I'd turned off the "Lint files on save" in the View menu. Did this as JSLint spouts out so much. Any idea on how I disable JSLint completely?

**Comment by zaggino** [comment]
I use these files in project roots: https://github.com/zaggino/brackets-eslint/blob/master/.brackets.json
You can also set it globally in brackets preferences.
JSLint should be moved out of default installation in next versions.
Until then you can go to your Brackets installation directory and delete /www/extensions/default/JSLint folder.
