### ISSUE TITLE
How to configure (missing link in README file)?

### ISSUE THREAD

**Issue by matronator** [zaggino/brackets-eslint#46]
So I have everything installed in brackets but only error it shows is when I put single (unclosed) curly bracket somewhere in the code. Otherwise it always shows green check mark even when there are errors. So I guess I must configure it somehow but I can't find clear instructions and the link to sample file in README.md is dead. How should the config file look, where do I put it and is there anything else that needs to be done in order for Brackets to be able to get all the files it needs?

**Comment by zaggino** [comment]
You configure it the same way you'd configure eslint without Brackets. Just place `.eslintrc` file in your project like you can see for example here: https://github.com/adobe/brackets

Read more here: http://eslint.org/docs/user-guide/configuring

**Comment by zaggino** [comment]
Extension should provide you the same results/checks that you get when you run `eslint .` from the command line/terminal of your project directory.

**Comment by zaggino** [comment]
Tip: go to your project folder and run:
```
npm install -g eslint
eslint --init
```
That will create a configuration file for you.

**Comment by matronator** [comment]
Thanks! :)
