### ISSUE TITLE
Legacy node process detected?

### ISSUE THREAD

**Issue by LaneLourcey** [zaggino/brackets-eslint#48]
I'm getting an error that says ESLintError: Legacy node process detected (0.10.24), please update to Brackets 1.8 or Brackets-Electron to support ESLint 3.5.0 /*

Now I am running brackets 1.8, so I'm not sure what is going on.

**Comment by zaggino** [comment]
@LaneLourcey 
Brackets team messed up the 1.8 installer, it contains old node instead of new one.
Brackets-Electron won't show the old error.
You can do `npm install eslint@2.x` in your project to keep using eslint 2.x that should work.
Legacy node won't work with eslint 3.x

**Comment by LaneLourcey** [comment]
Is there any way to figure out what version of eslint-config-airbnb-base I should use with eslint 2.13.1?

**Comment by zaggino** [comment]
ESLint 3.0 was released on 02/July - https://github.com/eslint/eslint/tree/v3.0.0
According to that, using 9.x should be fine: https://github.com/airbnb/javascript/tree/eslint-config-airbnb-v9.0.1 ... 10.x was released in August and probably requires ESLint v3
