### ISSUE TITLE
ESLintError: You need to install ESLint in your project folder....

### ISSUE THREAD

**Issue by UsulPro** [zaggino/brackets-eslint#49]
I have this error with intalled 3.5.0 eslint (with 2.7.0 everything is Ok)
`Brackets Release 1.8 build 1.8.0-17080`
`Windows 8.1`
```
"eslint-config-airbnb": "^11.1.0",
"eslint-plugin-babel": "^3.2.0",
"eslint-plugin-import": "^1.15.0",
"eslint-plugin-jsx-a11y": "^2.2.2",
"eslint-plugin-react": "^6.2.1",
```

**Comment by zaggino** [comment]
@UsulPro sadly pre-release installers got messed up, they don't contain node6 as they should but old node 0.10 which is not able to run eslint 3.
You can either:
a) use https://github.com/zaggino/brackets-electron/releases
b) wait for fixed pre-release installers, only people at Adobe can build them
