### ISSUE TITLE
how to set global eslint configuration?

### ISSUE THREAD

**Issue by JackPu** [zaggino/brackets-eslint#52]
I has installed brackets eslint. Is there any way to make eslint rules run in each project when I use brackets like jslint?

**Comment by zaggino** [comment]
Only `.eslintrc.*` files are supported which are mentioned here: http://eslint.org/docs/user-guide/configuring

Although it could be possible to define some defaults in the editor settings, it's better practice to use `.eslintrc.*` file in the root of your project(s). This way you can easier share the project between users who have different editors.
