### ISSUE TITLE
why my brackets complains about it need new version?

### ISSUE THREAD

**Issue by clouds56** [zaggino/brackets-eslint#56]
When I would like to install this plugin via Extension Manager, it complains about "This extension requires a newer version of Brackets."
FYI, I'm using macOS and install the brackets (version: Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700) via brew cask.

**Comment by NestorHernandezA** [comment]
Same here

**Comment by zaggino** [comment]
To install from extension manager you need at least Brackets 1.9, get pre-release here: https://github.com/adobe/brackets/releases

For usage with 1.8, check README file: https://github.com/zaggino/brackets-eslint

**Comment by zaggino** [comment]
Yes, you can install the ESLint package manually or using brackets-npm-registry.

But there's nothing unstable about pre-release and I'd recommend giving it a chance.

**Comment by clouds56** [comment]
All the thing that blocks me from trying 1.9 pre-release is `brew cask` doesn't recognize it. https://github.com/caskroom/homebrew-cask/blob/master/Casks/brackets.rb
But I wonder why there's explicit requirement "brackets >= 1.9"? Is there any compatible issue about 1.8?
I think most people would not stick to old version as long as "the package manager" (which is brew in macOS) notifies that there's a new version.

**Comment by zaggino** [comment]
@clouds56 1.8 can't install extensions with npm dependencies (my pr https://github.com/adobe/brackets/pull/10602 was merged for 1.9)

**Comment by clouds56** [comment]
Oh, thanks a lot! I'll look forward to the latest 1.9 version.

**Comment by Nosfy01** [comment]
Now that 1.9 is globally available, I installed the extension but I am totally unable to configure it (unless I use the comments in the file -> /* global es6 */).

As soon as i use a .eslintrc file it complains that I should run npm install some-eslint-stuff in my project folder. (the link to the example leads to a 404 page by the way)

I just want to use a html, css and javascript file in a folder for some testing. Will I have to run NPM stuff every time I want to create a new folder ? I don't want to become an expert at resolving npm dependencies, I just want to use Brackets in a "normal" environment.

Sounds to me like this community expects every Brackets user to also be a contributor and know everything about this project development.

**Comment by zaggino** [comment]
@Nosfy01 go to your project folder (same folder where `.eslintrc` is) and do `npm install eslint`. Extension will use eslint version that it finds in your project.

Reasoning is that extension itself comes with some semi-random version which works fine when you don't have any specific config but when you define a config, you also need to install your own eslint version (not every config would work with bundled version).
