### ISSUE TITLE
if an ".eslintrc" file is present in a project on Brackets startup, eslint fails

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-eslint#63]
This is **not** a nodejs project, but the error received is "ESLintError: You need to install ESLint in your project folder with 'npm install eslint'"

General info:
- Brackets version: Release 1.9 build 1.9.0-17312 
- macOS version: 10.12.5
- nodejs version (installed by Homebrew, project is not a node project): v8.1.3
- npm version: 5.0.4
- I'm able to reproduce the issue with only the Eslint plugin installed

Steps to recreate. There are additional steps added to show what works properly in contrast to what doesn't:

1. Open a project's javascript file in Brackets. The built-in linter shows any warnings.
2. Install Eslint. In addition to the built-in linter warnings, the Eslint warnings also properly show.
3. Reload Brackets by clicking "Debug-->Reload With Extensions". The Eslint warnings properly show.
4. Quit Brackets and restart it. The Eslint warnings properly show.
5. Create an ".eslintrc" file. The Eslint warnings properly show, and modifying the rc file correctly changes the warnings shown.
6. Reload Brackets by clicking "Debug-->Reload With Extensions". The Eslint warnings properly show.
7. Quit Brackets and restart it. Now Eslint fails with the above error message.

Other notes:

- Once the error occurs, reloading or restarting Brackets with the ".eslintrc" present does not fix the error.
- If you remove/rename the rc file and then reload or restart Brackets the error goes away.
- I tried with ".eslintrc", ."eslintrc.js", and ".eslintrc.json" with similar results.

**Comment by alvint** [comment]
The error still occurs if Eslint is installed globally.

**Comment by alvint** [comment]
same issue with Brackets Release 1.10 build 1.10.0-17483

**Comment by zaggino** [comment]
@alvint When you create `.eslintrc` file for example in `/home/alvint/project1` you need to go to directory `/home/alvint/project1` and do `npm install eslint` in there, not globally.

Reason for this is that different `.eslintrc` configs work with different ESLint versions so you should always have ESLint installed in the project you're working on.

**Comment by alvint** [comment]
Thanks for the reply (and the many great plugins, BTW).

This is not a Nodejs project, so I'd rather not have to deal with a `node_modules` folder and the other stuff if I can help it.  I also don't want to require that other developers install Node if I can help it, but I **do** want to strongly recommend Brackets and Eslint.

I don't mind if `.eslintrc` is locked to whatever version is in your plugin, especially since the config file will be shared. Since it seems to work if you rename the file and back again (see above), would it be possible to just do that automatically on startup?

**Comment by lkcampbell** [comment]
@zaggino, this is a great extension, thanks for your work on it.

I just started using it today and ran into this issue almost immediately. Just to make sure I understand this issue correctly. The only way I can have a local ESLint configuration file is if I am working on a Node.js project?

**Comment by zaggino** [comment]
@lkcampbell 
The only thing you need to do is have node.js installed and do
`npm install eslint@x.y.z` in your project folder where `x.y.z` is your desired eslint version that you want to use with your `.eslintrc` file. In case you don't care about the version, just do `npm install eslint`. It doesn't have to be a node.js project, it can be project in any language, framework, whatever. `npm install eslint` command will install desired version to your project and `brackets-eslint` extension will use this version when checking your code.

**Comment by lkcampbell** [comment]
@zaggino, I understand. Is it possible to just use the version of the ESLint that you already supply, like @alvint is suggesting? I realize there might be compatibility problems introduced in the config file but those could be addressed if they arise. Maybe a Brackets preferences to allow it?

**Comment by zaggino** [comment]
@lkcampbell you can setup a preference which would disable this warning, I'm happy to accept a PR but the default behaviour should stay.

**Comment by lkcampbell** [comment]
@zaggino, of course. That's why Brackets preferences exist, my friend. Different strokes for different folks and all that.

Thanks for keeping an open mind. I will work on the PR this weekend.

**Comment by zaggino** [comment]
Fixed in https://github.com/zaggino/brackets-eslint/pull/65
Please see README

**Comment by shaunhurley** [comment]
@zaggino @lkcampbell 

Gents, I am encountering this error and found this conversation, which I read with interest.

I am aware of the "brackets-eslint.useLocalESLint" directive in the brackets.json config files, and that I can  do a local "npm install eslint" within a project directory and use a local .eslintrc.json or similar to provide a local configuration for the locally installed instance.

If trying to avoid doing a local ESLint install in every project directory, is there a means and/or documentation on how to pass configuration options to the instance of ESLint that is distributed with Brackets 1.11? Either through the brackets.json file or otherwise (possibly a global config file in the extension directory)?

I've spent a good portion of my afternoon trying to find and answer without luck, so any guidance would be much appreciated!

**Comment by alvint** [comment]
Hi, @shaunhurley,

After this fix, adding a `.eslintrc` file to my project folder works for me even though I also don't install ESLint locally. It's not working for you? Or are you trying to create a default config that all projects opened with Brackets use?

**Comment by shaunhurley** [comment]
It is now that I un-confused myself :)

I misread the intent of the "brackets-eslint.useLocalESLint" directive as "true" == use-an-instance-of-ESLint-installed-in-the-project-directory which is the opposite of what it is actually doing.

**Comment by alvint** [comment]
Wow, now that you mention it that is indeed really confusing. @zaggino, you may want to consider changing the name, but I guess you can't do that because it would break existing configurations. Maybe adding a synonym and undocumenting the previous directive?

**Comment by josezulu** [comment]
@zaggino 
I just run into this very same issue on Brackets ver 1.13.

With a local .eslintrc file, eslint did not work (would ask me to install locally).
Changing "brackets-eslint.useLocalESLint" from "false" to "true" fixed the issue.

This variable name needs to be renamed to match it's intent, or it's check reversed from true to false.
