### ISSUE TITLE
Dilato: Core: The default version of ESLint is inconsistent with the version in the More info link

### ISSUE THREAD

**Issue by ZuoBaogang** [zaggino/brackets-eslint#66]
Steps:
1. Launch Brackets
2. Open extension manager
3. Find the ESLint under Default tab then observe the version is 3.0.5
4. Click "More info..."
5. The version is 3.1.0

Result: The default version of ESLint is inconsistent with the version in the More info link

Expect: They should keep consistent
![defaultversion](https://user-images.githubusercontent.com/17721679/30026299-e05bf57c-91ae-11e7-8b89-14375e761b98.png)
![moreinfoversion](https://user-images.githubusercontent.com/17721679/30026300-e160d7da-91ae-11e7-8fe8-9058f6ef37ae.png)

**Comment by ZuoBaogang** [comment]
ESLint appears both under Available tab and Default tab, is this by design?

**Comment by zaggino** [comment]
cc @swmitra
