### ISSUE TITLE
Version 3.1.1 produces error message

### ISSUE THREAD

**Issue by lkcampbell** [zaggino/brackets-eslint#68]
I updated to the latest version today and all I am getting is the following error message:

`EsLint terminated with error: {1}`

This is happening on both my Mac OS and my Windows Surface.

**Comment by zaggino** [comment]
@lkcampbell My bad, https://github.com/zaggino/brackets-eslint/commit/cd8a4a41115e6ad9322f8857e9c4316e25858d64 fixes this.
