### ISSUE TITLE
Unable to load plugins

### ISSUE THREAD

**Issue by globexdesigns** [zaggino/brackets-eslint#8]
In my .eslintrc I have this:

```
plugins:
  - react
```

And I have the `eslint-plugin-react` module installed both inside my project root and globally (via `npm install -g eslint-plugin-react). However, brackets-eslint still displays this error:

```
ESLint terminated with error: Cannot find module 'eslint-plugin-react'
```

**Comment by zaggino** [comment]
@globexdesigns plugins has to be supported case by case, I didn't find a way to use globally installed ones so far, I've added `react` plugin to the version `0.18.1`

**Comment by globexdesigns** [comment]
Thanks! Would it also be possible to add support for `babel-eslint`?

**Comment by zaggino** [comment]
Why would you need `babel-eslint` ? Latest `espree` which is default parser for ESLint supports full ES6 now, or not?

**Comment by zaggino** [comment]
Added in `0.18.2`

**Comment by globexdesigns** [comment]
Unfortunately `esprima-fb` doesn't support destructuring spread attributes, ie:

```
var { className, ...other } = this.props;
```

It throws this error:

```
/usr/local/lib/node_modules/eslint/node_modules/escope/escope.js:904
                            if (property.value.type === Syntax.Identifier) {
                                              ^
TypeError: Cannot read property 'type' of undefined
```

Whereas `babel-eslint` works just fine.

And the esprima team said they will not be fixing this: https://github.com/eslint/espree/issues/116

**Comment by zaggino** [comment]
Didn't knew that :) Thanks for the info. As mentioned, I've added support to the latest version.

Out of curiosity, do you know if `babel-eslint` supports ES7 stuff like `async/await`?

**Comment by globexdesigns** [comment]
Not sure. Sorry. But it seems to do a much better job at supporting React's JSX syntax than esprima-fb for some reason.

**Comment by zaggino** [comment]
`esprima-fb` is now going to be deprecated - http://bit.ly/1DD1zsv
