### ISSUE TITLE
Add support for AngularJS

### ISSUE THREAD

**Issue by hindsholm** [zaggino/brackets-eslint#9]
Nice Brackets plugin!

I just wish there were support for AngularJS.
There is a very good ESLint plugin for this: [eslint-plugin-angular](https://github.com/Gillespie59/eslint-plugin-angular).

**Comment by zaggino** [comment]
Thanks. Added `eslint-plugin-angular` to the latest version.

**Comment by hindsholm** [comment]
That was fast! Thank you.

**Comment by kamikaz1k** [comment]
Hey guys, how do you integrate eslint-plugin-angular?
I tried installing it within the Brackets\extensions\user\brackets-eslint directory, but the angular rules were being marked as undefined rules.

I also tried installed the plugin globally, but the same error persisted.
@hindsholm your help would be appreciated!

**Comment by zaggino** [comment]
@kamikaz1k brackets-eslint should now pick it up from your project if you do:
```
npm install --save-dev eslint eslint-plugin-angular
```
